development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://localhost:3001
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: call_api_production
